id: P009178
initial_creation_type: ocr
source_metadata:
  id: bdr:W30525
  title: བོད་ལུགས་གསོ་རིག་མཁས་དབང་གི་ཉམས་མྱོང་སྙིང་བསྡུས།
  author: ''
  volumes:
    ee730e9a9abc4c78a86934f415141370:
      image_group_id: I1KG16922
      title: ''
      volume_number: 1
      total_pages: 174
      base_file: v001.txt
