id: I79579893
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:12:17+00:00'
last_modified: '2022-06-08T09:10:30.596680+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30525
  title: བོད་ལུགས་གསོ་རིག་མཁས་དབང་གི་ཉམས་མྱོང་སྙིང་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3974':
      image_group_id: I1KG16922
      title: ''
      total_pages: 174
      order: 1
      base_file: 3974.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
